server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://campuslink-db.cz84m6ekwz59.ap-southeast-2.rds.amazonaws.com:3306/campuslink?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: campuslink_app      # 예: admin 또는 campuslink_app
    password: campus1234!
  jpa:
    hibernate:
      ddl-auto: validate       # 초기엔 update 가능, 스키마 확정 후 validate 권장
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.hibernate.SQL: debug   # (선택) 실행 쿼리 로그
